### ISSUE TITLE
features for maybe new project?

### ISSUE THREAD

**Issue by maxcamorra** [nbgibson/streamers#1]
hey now that you get to check who is online it would be so nice to get another project which works with this one here to build like a twitch points miner.
Basically you check who of your followed streamer is live and then you automatically join the chat to gain points at twitch/streamelements and also watchtime. when the streamer gets offline you leave the chat to not have offline chat time.
it would be possible if you could do something like this.

**Comment by nbgibson** [comment]
This could pretty reasonably be accomplished via a number of means, but I would wonder if it would be a violation of Twitch TOS as it could be utilized to artificially inflate viewcount and cause undeserved payouts and so on. I do have plans to work [Streamlink](https://streamlink.github.io/) integration into this script down the line, but I believe points and so on are all on the website's side so that wouldn't help too much I'm afraid.

**Comment by nbgibson** [comment]
You may find this of note: https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2
